# Use root/example as user/password credentials
version: '3.9'
services:
  db:
    container_name: blog-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql-volume: